# Prep the new RNA editing genes from Tom for network z-score processing 

Update 5/9/19: slightly new lists- need to reprocess

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import networkx as nx
import seaborn as sns

from IPython.display import display

import community

import mygene
mg = mygene.MyGeneInfo()

# latex rendering of text in graphs
import matplotlib as mpl
mpl.rc('text', usetex = False)
mpl.rc('font', family = 'sans-serif')
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Arial']

% matplotlib inline

import visJS2jupyter.visJS_module
import visJS2jupyter.visualizations

# Load the gene sets

In [2]:
AMLvsAN_df = pd.read_csv('../data/190509/differentially_edited_genes_AMLvsAN_progenitors_noIGR_padj_190508_rev.txt',
                        sep='\t')
print(len(AMLvsAN_df))
print(AMLvsAN_df['p.adjust'].max())
AMLvsAN_genes = list(np.unique(AMLvsAN_df['Gene']))
print(len(AMLvsAN_genes))
AMLvsAN_df.head()

757
0.004953038
744

,p.value,p.adjust,chi_square_statistic,Gene,n_cond1,n_cond2,n_samples_cond1,n_samples_cond2,n_possible_sites_cond1,n_possible_sites_cond2,p.adjust2
0,8.990000e-52,3.770000e-48,229.182173,SPN,8,148,12,8,600,400,3.980000e-45
1,1.210000e-44,2.540000e-41,196.499832,EIF2AK2,19,147,12,8,552,368,2.680000e-38
2,4.360000e-41,6.100000e-38,180.208521,GABPB1-AS1,0,110,12,8,672,448,6.420000e-35
3,3.720000e-34,3.900000e-31,148.482286,CCAR1,6,103,12,8,612,408,4.100000e-28
4,6.380000e-34,5.350000e-31,147.411200,HOOK3,0,89,12,8,480,320,5.620000e-28

In [3]:
MFvsAN_df = pd.read_csv('../data/190509/differentially_edited_genes_MFvsAN_progenitors_noIGR_padj_190508_rev.txt',
                        sep='\t')
print(len(MFvsAN_df))
MFvsAN_genes = list(np.unique(MFvsAN_df['Gene']))
print(len(MFvsAN_genes))
print(MFvsAN_df['p.adjust'].max())
MFvsAN_df.head()

834
815
0.004941926

,p.value,p.adjust,chi_square_statistic,Gene,n_cond1,n_cond2,n_samples_cond1,n_samples_cond2,n_possible_sites_cond1,n_possible_sites_cond2,p.adjust2
0,2.120000e-92,1.310000e-88,415.686662,SPN,7,148,22,8,1078,392,1.510000e-85
1,2.890000e-68,8.950000e-65,304.852229,GABPB1-AS1,3,110,22,8,1276,464,1.030000e-61
2,5.230000e-63,1.080000e-59,280.722448,CCAR1,4,103,22,8,1144,416,1.240000e-56
3,3.370000e-55,5.220000e-52,244.896369,HOOK3,3,89,22,8,946,344,5.970000e-49
4,1.640000e-54,2.030000e-51,241.741453,CCDC84,3,88,22,8,946,344,2.320000e-48

In [4]:
AMLvsMF_df = pd.read_csv('../data/190509/differentially_edited_genes_AMLvsMF_progenitors_noIGR_padj_190508_rev.txt',
                        sep='\t')
print(len(AMLvsMF_df))
AMLvsMF_genes = list(np.unique(AMLvsMF_df['Gene']))
print(len(AMLvsMF_genes))
print(AMLvsMF_df['p.adjust'].max())
AMLvsMF_df.head()

158
155
0.004895878

,p.value,p.adjust,chi_square_statistic,Gene,n_cond1,n_cond2,n_samples_cond1,n_samples_cond2,n_possible_sites_cond1,n_possible_sites_cond2,p.adjust2
0,1.600000e-20,8.830000e-17,86.236465,S100Z,78,21,12,22,492,902,2.290000e-14
1,3.640000e-20,1.010000e-16,84.607867,PSMB2,17,157,12,22,144,264,2.600000e-14
2,2.810000e-17,5.180000e-14,71.474092,DFFA,19,197,12,22,876,1606,1.330000e-11
3,5.670000e-17,7.020000e-14,70.088542,RNF220,270,246,12,22,2412,4422,1.800000e-11
4,6.350000e-17,7.020000e-14,69.865734,TEC,5,143,12,22,696,1276,1.800000e-11

# Write out gene lists for AWS processing

In [5]:
# write out seed genes for AWS processing

pd.DataFrame({'seed_genes':[AMLvsAN_genes]}).to_csv('AMLvsAN_seed_genes_190509.tsv',sep='\t')
pd.DataFrame({'seed_genes':[MFvsAN_genes]}).to_csv('MFvsAN_seed_genes_190509.tsv',sep='\t')
pd.DataFrame({'seed_genes':[AMLvsMF_genes]}).to_csv('AMLvsMF_seed_genes_190509.tsv',sep='\t')